application:
  subdomain: self-music
  background_task: true
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://self-music:80/
services:
  self-music:
    # upstream: zkeq/self-music:1.0.6
    image: docker.1ms.run/zkeq/self-music:1.0.6
    binds:
      - /lzcapp/var/data:/data
