name: Self Music
package: community.lazycat.app.self-music
version: 1.0.5
min_os_version: 1.3.8
description: 🌟 一个现代化的私人音乐管理与播放系统，支持播放列表、歌词同步与多端访问。（支持一键导入网易云音乐元数据，批量搜刮的私人音乐客户端）
homepage: https://github.com/zkeq/Self-Music
author: zkeq
application:
  subdomain: self-music
  background_task: true
  public_path:
    - /

  upstreams:
    - location: /
      backend: http://self-music:80/
services:
  self-music:
    container_name: self-music
    # zkeq/self-music:1.0.5
    image: registry.lazycat.cloud/czyt/zkeq/self-music:d48b947a2304d275
    binds:
      - /lzcapp/var/data:/data

locales:
  zh:
    name: "Self Music"
    description: "🌟 一个现代化的私人音乐管理与播放系统，支持播放列表、歌词同步与多端访问。（支持一键导入网易云音乐元数据，批量搜刮的私人音乐客户端）"
  en:
    name: "Self Music"
    description: "🌟 A modern private music management and playback system, supporting playlists, lyrics synchronization, and multi-device access. (Supports one-click import of NetEase Cloud Music metadata, a batch scraping private music client)"
